# Generated by Django 5.2.12 on 2026-03-08 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_slots(apps, schema_editor):
    SessionOccurrence = apps.get_model("club_sessions", "SessionOccurrence")
    SessionSlot = apps.get_model("club_sessions", "SessionSlot")

    for occurrence in SessionOccurrence.objects.all().iterator():
        SessionSlot.objects.get_or_create(
            occurrence=occurrence,
            sequence_index=1,
            defaults={
                "start_time": occurrence.start_time,
                "end_time": occurrence.end_time,
                "capacity": occurrence.capacity,
                "status": occurrence.status,
                "notes": "",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_index', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('auto_cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='club_sessions.sessionoccurrence')),
            ],
            options={
                'ordering': ['occurrence__session_date', 'start_time', 'sequence_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResponsibleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('release_reason', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_assignment_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_assignments', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_assignments', to='club_sessions.sessionslot')),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionslot',
            constraint=models.UniqueConstraint(fields=('occurrence', 'sequence_index'), name='unique_slot_sequence_per_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='responsibleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('slot',), name='unique_active_responsable_per_slot'),
        ),
        migrations.RunPython(create_initial_slots, migrations.RunPython.noop),
    ]
