# Generated by Django 5.2.12 on 2026-03-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0002_sessionslot_responsibleassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=7)),
                ('cancellation_days_before', models.PositiveSmallIntegerField(default=2)),
                ('reminder_email_subject', models.CharField(default='Creneau sans responsable le {session_date}', max_length=255)),
                ('reminder_email_body', models.TextField(default='Bonjour,\n\nLe creneau {slot_start}-{slot_end} de {session_label} le {session_date} n a pas encore de responsable.\nMerci de vous positionner si vous pouvez le couvrir.')),
                ('cancellation_email_subject', models.CharField(default='Annulation du creneau {session_label}', max_length=255)),
                ('cancellation_email_body', models.TextField(default='Bonjour,\n\nLe creneau {slot_start}-{slot_end} de {session_label} le {session_date} est annule faute de responsable.\nMerci de votre comprehension.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
