# Generated by Django 5.2.12 on 2026-03-18 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0003_emailautomationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionoccurrence',
            name='session_type',
            field=models.CharField(choices=[('free_practice', 'Pratique libre'), ('course', 'Cours')], default='free_practice', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionoccurrence',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionseries',
            name='default_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_course_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionseries',
            name='session_type',
            field=models.CharField(choices=[('free_practice', 'Pratique libre'), ('course', 'Cours')], default='free_practice', max_length=20),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_course_enrollments', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_course_enrollments', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='club_sessions.sessionseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__full_name', 'series__label', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'series'), name='unique_active_course_enrollment_per_user_series')],
            },
        ),
    ]
