# Generated by Django 5.2.13 on 2026-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0004_sessionoccurrence_session_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('removed', 'Retiré')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='responsibleassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('released', 'Libéré'), ('revoked', 'Révoqué')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionoccurrence',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouverte'), ('closed', 'Fermée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionseries',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')]),
        ),
        migrations.AlterField(
            model_name='sessionslot',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert'), ('closed', 'Fermé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='draft', max_length=20),
        ),
    ]
