# Generated by Django 5.2.13 on 2026-04-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0005_alter_courseenrollment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSeriesSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_index', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='club_sessions.sessionseries')),
            ],
            options={
                'ordering': ['sequence_index', 'start_time', 'id'],
            },
        ),
    ]
