# Generated by Django 5.2.12 on 2026-03-08 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_responsable_accredited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='responsable_accredited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='responsable_accredited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_responsable_accreditations', to=settings.AUTH_USER_MODEL),
        ),
    ]
