# Generated by Django 5.2.12 on 2026-03-18 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_responsable_accredited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_orange_passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='orange_passport_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orange_passport_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_orange_passports', to=settings.AUTH_USER_MODEL),
        ),
    ]
