# Generated by Codex on 2026-03-18

from django.db import migrations, models


def mark_existing_temporary_passwords_active(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(password_state="temporary").update(password_state="active")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_has_orange_passport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_state",
            field=models.CharField(
                choices=[
                    ("temporary", "Temporary"),
                    ("active", "Active"),
                    ("reset_required", "Reset required"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            mark_existing_temporary_passwords_active,
            migrations.RunPython.noop,
        ),
    ]
