# Generated by Django 5.2.12 on 2026-03-19 10:40

import re
import unicodedata

from django.db import migrations, models


_NON_ALNUM_RE = re.compile(r"[^a-z0-9]+")


def _build_login_key(full_name: str | None) -> str:
    normalized = unicodedata.normalize("NFKD", (full_name or "").strip())
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii").lower()
    return _NON_ALNUM_RE.sub("", ascii_value)


def populate_login_keys(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    seen_keys: set[str] = set()
    for user in User.objects.order_by("id"):
        login_key = _build_login_key(user.full_name)
        if not login_key:
            raise ValueError(f"User {user.pk} has no usable full name for login_key.")
        if login_key in seen_keys:
            raise ValueError(f"Duplicate login_key generated for {user.full_name}.")
        seen_keys.add(login_key)
        user.login_key = login_key
        if user.email == "":
            user.email = None
        user.save(update_fields=["login_key", "email"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_password_state_active_by_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="login_key",
            field=models.CharField(default="", editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(populate_login_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="login_key",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
