# Generated by Django 5.2.12 on 2026-04-11 12:00

from django.db import migrations, models


def backfill_course_teachers(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    SessionSeries = apps.get_model("club_sessions", "SessionSeries")
    SessionOccurrence = apps.get_model("club_sessions", "SessionOccurrence")

    teacher_ids = set(
        SessionSeries.objects.exclude(default_teacher_id=None).values_list("default_teacher_id", flat=True)
    )
    teacher_ids.update(
        SessionOccurrence.objects.exclude(teacher_id=None).values_list("teacher_id", flat=True)
    )
    if teacher_ids:
        User.objects.filter(pk__in=teacher_ids).update(can_teach_courses=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_login_key_optional_email"),
        ("club_sessions", "0004_sessionoccurrence_session_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_teach_courses",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_course_teachers, migrations.RunPython.noop),
    ]
