# Generated by Django 5.2.13 on 2026-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_can_teach_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_state',
            field=models.CharField(choices=[('temporary', 'Temporaire'), ('active', 'Actif'), ('reset_required', 'Changement de code requis')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Adhérent'), ('admin', 'Administrateur')], default='member', max_length=20),
        ),
    ]
