# Generated by Django 5.2.12 on 2026-03-08 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_reservation_slots(apps, schema_editor):
    Reservation = apps.get_model("bookings", "Reservation")
    SessionSlot = apps.get_model("club_sessions", "SessionSlot")

    for reservation in Reservation.objects.filter(slot__isnull=True).iterator():
        slot = SessionSlot.objects.filter(occurrence_id=reservation.occurrence_id).order_by("sequence_index", "id").first()
        if slot is not None:
            reservation.slot_id = slot.pk
            reservation.save(update_fields=["slot"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('club_sessions', '0002_sessionslot_responsibleassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_active_reservation_per_user_occurrence',
        ),
        migrations.AddField(
            model_name='reservation',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='club_sessions.sessionslot'),
        ),
        migrations.RunPython(backfill_reservation_slots, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='reservation',
            name='occurrence',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('slot', 'user'), name='unique_active_reservation_per_user_slot'),
        ),
    ]
