# Generated by Codex on 2026-03-08

import django.db.models.deletion
from django.db import migrations, models


def backfill_occurrence_from_slot(apps, schema_editor):
    Reservation = apps.get_model("bookings", "Reservation")
    for reservation in Reservation.objects.filter(occurrence__isnull=True, slot__isnull=False).iterator():
        reservation.occurrence_id = reservation.slot.occurrence_id
        reservation.save(update_fields=["occurrence"])


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_remove_reservation_unique_active_reservation_per_user_occurrence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="occurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="club_sessions.sessionoccurrence",
            ),
        ),
        migrations.RunPython(backfill_occurrence_from_slot, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("occurrence", "user"),
                name="unique_active_reservation_per_user_occurrence_v2",
            ),
        ),
    ]
