# Generated by Django 5.2.13 on 2026-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_reservation_occurrence_back_to_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Confirmée'), ('cancelled', 'Annulée')], default='active', max_length=20),
        ),
    ]
