# Generated by Django 5.2.12 on 2026-03-08 14:40

import django.db.models.deletion
from django.db import migrations, models


def backfill_audit_slot_context(apps, schema_editor):
    AuditEntry = apps.get_model("audit", "AuditEntry")
    SessionSlot = apps.get_model("club_sessions", "SessionSlot")

    for entry in AuditEntry.objects.filter(slot__isnull=True).iterator():
        slot_id = None
        if entry.reservation_id:
            reservation = entry.reservation
            slot_id = getattr(reservation, "slot_id", None)
        if slot_id is None and entry.occurrence_id:
            slot = SessionSlot.objects.filter(occurrence_id=entry.occurrence_id).order_by("sequence_index", "id").first()
            slot_id = slot.pk if slot else None
        if slot_id is not None:
            entry.slot_id = slot_id
            entry.save(update_fields=["slot"])


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('bookings', '0002_remove_reservation_unique_active_reservation_per_user_occurrence_and_more'),
        ('club_sessions', '0002_sessionslot_responsibleassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='responsible_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='club_sessions.responsibleassignment'),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='club_sessions.sessionslot'),
        ),
        migrations.RunPython(backfill_audit_slot_context, migrations.RunPython.noop),
    ]
